version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Vince-Bloise-Resume-2018-c1.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
